AllCops:
  TargetRubyVersion: 2.6
  # Include common Ruby source files.
  Include:
    - '**/*.rb'
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/*.opal'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'
    - '**/Fastfile'
    - '**/*Fastfile'
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/support/body_helper.rb'
    - 'config/environments/*'
    - 'test/channels/application_cable/*'
    - 'test/test_helper.rb'
    - 'config/initializers/*'

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Metrics/LineLength:
  Max: 140
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'define']

Naming/MemoizedInstanceVariableName:
  Enabled: false

